# makefile for tests in this dir
CC = gcc 

all: test_parser test_network

test_parser: test_parser.c
	gcc test_parser.c -o ./bin/test_parser

test_network: test_network.c 
	gcc test_network.c -o ./bin/test_network
